Project=CEP V2 Automation
Application=CEP V2 Whiteboard & Playlist
Environment=QA / Staging
Framework=Cypress 13 (Page Object Model)
Browser=Google Chrome (Headless)
BaseURL=https://ce-qa-school.devstudi.com/teach/whiteboard
Total Scenarios=60 Automated Scenarios